on:
  push:
  pull_request:
    
jobs:
  test_lint:
    strategy:
      matrix:
        os: [ubuntu-latest ]
        zig_version: [master]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.zig_version }}
      - run: zig fmt --check src/*.zig *.zig *.zon
      - run: zig build test
